// Simulated blockchain layer for Vica BlockLedger prototype.
// Wallet connection uses real wagmi/viem (injected connector / MetaMask),
// but on-chain writes are SIMULATED — we never send real ETH or call a real
// contract. This keeps the prototype safe while demonstrating the workflow.
//
// Only non-PII data is included in the simulated payload:
//   - transaction id (TRX-xxx)
//   - status / activity code
//   - local hash digest of the order
// We deliberately exclude customer name, phone, and any personal data.

export const VICA_LEDGER_CONTRACT = "0xV1CA0000000000000000000000000000000000Led" as const;

// Minimal ABI we would target on a real chain.
export const VICA_LEDGER_ABI = [
  {
    type: "function",
    stateMutability: "nonpayable",
    name: "recordActivity",
    inputs: [
      { name: "orderId", type: "string" },
      { name: "orderHash", type: "bytes32" },
      { name: "activityCode", type: "string" },
    ],
    outputs: [{ name: "txHash", type: "bytes32" }],
  },
  {
    type: "event",
    name: "ActivityRecorded",
    inputs: [
      { indexed: true, name: "orderId", type: "string" },
      { indexed: false, name: "orderHash", type: "bytes32" },
      { indexed: false, name: "activityCode", type: "string" },
      { indexed: false, name: "timestamp", type: "uint256" },
    ],
  },
] as const;

export type BlockchainAction =
  | "VERIFY_PAYMENT"
  | "MARK_ISSUE"
  | "START_PACKING"
  | "MARK_READY"
  | "CONFIRM_PICKUP";

export const ACTION_LABEL: Record<BlockchainAction, string> = {
  VERIFY_PAYMENT: "Verifikasi Pembayaran",
  MARK_ISSUE: "Transaksi Bermasalah",
  START_PACKING: "Mulai Packing",
  MARK_READY: "Siap Diambil",
  CONFIRM_PICKUP: "Barang Sudah Diambil",
};

// Deterministic, locally-generated bytes32-like hex string used to stand in
// for a real transaction hash. NOT a cryptographic guarantee — prototype only.
export function simulateTxHash(payload: string): string {
  let h1 = 0x811c9dc5;
  let h2 = 0xdeadbeef;
  for (let i = 0; i < payload.length; i++) {
    const c = payload.charCodeAt(i);
    h1 = Math.imul(h1 ^ c, 16777619);
    h2 = Math.imul(h2 ^ c, 2246822519);
  }
  const hex = (n: number) => (n >>> 0).toString(16).padStart(8, "0");
  const seed = hex(h1) + hex(h2) + hex(h1 ^ h2) + hex(Math.imul(h1, h2));
  // pad to 64 hex chars
  return ("0x" + (seed + seed).slice(0, 64)) as string;
}

export function buildChainPayload(orderId: string, orderHash: string, action: BlockchainAction) {
  return {
    contract: VICA_LEDGER_CONTRACT,
    method: "recordActivity",
    args: [orderId, orderHash, action] as const,
  };
}
